### ISSUE TITLE
Thumb not rendered correctly on Edge

### ISSUE THREAD

**Issue by aeirola** [Wikiki/bulma-slider#18]
The top edge of the thumb is hidden. Also, the thumb doesn't seem to be vertically aligned with the track. See screenshots for comparison with chrome:

Edge 41.16299.371.0:
<img width="706" alt="screen shot 2018-04-25 at 8 25 24" src="https://user-images.githubusercontent.com/1143250/39228101-e5be1b40-4864-11e8-8354-9d271ec688bf.png">

Chrome 66.0.3359.117:
<img width="640" alt="screen shot 2018-04-25 at 8 25 35" src="https://user-images.githubusercontent.com/1143250/39228105-e951d1f2-4864-11e8-9676-03a4f62e2d07.png">

As a workaround I've added something like this into my styles.
```scss
// Fix slider on Edge //
input[type=range].slider {
  height: $size-normal * 1.5;

  &::-ms-thumb {
    margin-top: 1px;
  }
}
```
